# Generated by Django 2.2.7 on 2019-12-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=200)),
                ('promo', models.TextField()),
                ('body', models.TextField()),
                ('headline', models.CharField(max_length=300)),
                ('publish_at', models.DateTimeField(verbose_name='date published')),
                ('byline', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=500)),
                ('instruments', models.CharField(max_length=500)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('comment_text', models.TextField()),
                ('comment_date', models.DateTimeField()),
            ],
        ),
    ]
