# Generated by Django 2.2.7 on 2019-12-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='article_uuid',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
